name: Scrape data

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  start_scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run : yarn install --frozen-lockfile

      - name: Start scraping data
        run : yarn run run:scrape

      - name: Commit and push changes
        run: |-
          git config user.name "brokiem"
          git config user.email "${{ secrets.EMAIL }}"
          git add -A
          timestamp=$(date -u)
          git commit -m "[BOT] Update sentences data" || exit 0
          git push
